apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: waypoint
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  description: HashiCorp Waypoint
  sourceRepos:
  - 'https://helm.releases.hashicorp.com'
  - 'https://github.com/nhsy-hcp/terraform-aws-eks-argocd.git'

  # Only permit applications to deploy to the vault namespace in the same cluster
  destinations:
  - namespace: waypoint
    server: https://kubernetes.default.svc
    name: in-cluster

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'admissionregistration.k8s.io'
    kind: MutatingWebhookConfiguration

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to waypoint
    policies:
    - p, proj:waypoint:read-only, applications, get, waypoint/*, allow
    groups:
    - waypoint
