apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

  project: vault

  sources:
    # Deploy Vault Helm chart
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.25.0
      helm:
        releaseName: vault
        valueFiles:
          - $values/argocd/hcp/vault-values.yaml

    # Use values from demo repository for Helm chart
    - repoURL: 'https://github.com/nhsy-hcp/terraform-aws-eks-argocd.git'
      targetRevision: argocd
      ref: values

  # Deploy to the vault namespace in same cluster
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
