global:
  enabled: true
  tlsDisable: false

injector:
  enabled: false

server:
  ha:
    enabled: true
    replicas: 3
    apiAddr: "https://$(VAULT_K8S_POD_NAME).vault-internal:8200"
    raft:
      enabled: true
      setNodeId: true
      config: |        
        listener "tcp" {
          tls_disable   = false
          tls_cert_file = "/vault/userconfig/tls/tls.crt"
          tls_key_file  = "/vault/userconfig/tls/tls.key"
        
          tls_require_and_verify_client_cert = false
          tls_disable_client_certs           = true
        
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"

          retry_join {
            auto_join             = "provider=k8s namespace=vault label_selector=\"component=server,app.kubernetes.io/instance=vault\""
            auto_join_scheme      = "https"
            leader_ca_cert_file   = "/vault/userconfig/tls-ca/ca.crt"
            leader_tls_servername = "HOSTNAME.vault-internal"
          }
        }

        service_registration "kubernetes" {}

        api_addr     = "https://HOSTNAME.vault-internal:8200"
        cluster_addr = "https://HOSTNAME.vault-internal:8201"        
        ui           = true
  extraVolumes:
    - type: secret
      name: tls
    - type: secret
      name: tls-ca
  extraEnvironmentVars:
    VAULT_CAPATH: /vault/userconfig/tls-ca/ca.crt
    VAULT_SKIP_VERIFY: true
  ingress:
    enabled: true
    annotations: |
      alb.ingress.kubernetes.io/group.name: "eks-hcp-shared"
      alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:188030499835:certificate/5dcd7953-1d53-41e5-9184-65da6c6135e0"
      alb.ingress.kubernetes.io/healthcheck-path: "/v1/sys/health"
      alb.ingress.kubernetes.io/listen-ports: "[{\"HTTPS\":443}]"
      alb.ingress.kubernetes.io/success-codes: "200"
      alb.ingress.kubernetes.io/target-type: "ip"
      kubernetes.io/ingress.class: "alb"

    hosts:
      - host: vault.narish-samplay.aws.sbx.hashicorpdemo.com
        paths: [/]

    tls:
      - hosts:
        - vault.narish-samplay.aws.sbx.hashicorpdemo.com

ui:
  enabled: false
